server:
  port: 5000
management:
  endpoint:
    health:
        show_details: "always"
  endpoints:
      web:
          exposure:
            include: "prometheus, health, info"
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:memdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${LOCALEMAIL}
    password: ${EMAILPASSWORD}
    port: '587'